const actionTypes = {
    AUTHORIZATION: 'AUTHORIZATION',
    LOGOUT: 'LOGOUT',
    REFRESHING_TOKEN: 'REFRESHING_TOKEN',

    GET_TABLE_SUCCESS: 'GET_TABLE_SUCCESS',
    GET_TABLE_ERROR: 'GET_TABLE_ERROR',
    CLEAR_TABLE: 'CLEAR_TABLE',
    UPDATE_TABLE: 'UPDATE_TABLE',
    SET_UPDATING_ITEM: 'SET_UPDATING_ITEM',
    CLEAR_UPDATING_ITEM: 'CLEAR_UPDATING_ITEM',

    COMPONENT_DATA_IS_FETCHING: 'COMPONENT_DATA_IS_FETCHING',
    COMPONENT_DATA_IS_FETCHED: 'COMPONENT_DATA_IS_FETCHED',
    CLEAR_COMPONENT_DATA: 'CLEAR_COMPONENT_DATA',

    GET_DATA_FOR_EDIT: 'GET_DATA_FOR_EDIT',
    GET_DESCRIPTORS_FOR_EDIT: 'GET_DESCRIPTORS_FOR_EDIT'
};

export default actionTypes;