const actionTypes = {
    AUTHORIZATION: 'AUTHORIZATION',
    LOGOUT: 'LOGOUT',
    REFRESHING_TOKEN: 'REFRESHING_TOKEN',

    GET_TABLE_SUCCESS: 'GET_TABLE_SUCCESS',
    GET_TABLE_ERROR: 'GET_TABLE_ERROR',
    CLEAR_TABLE: 'CLEAR_TABLE',
    UPDATE_TABLE: 'UPDATE_TABLE',
    SET_UPDATING_ITEM: 'SET_UPDATING_ITEM',
    CLEAR_UPDATING_ITEM: 'CLEAR_UPDATING_ITEM',

    GET_TYPE_PERMISSIONS: 'GET_TYPE_PERMISSIONS',
    GET_FORM_DESCRIPTOR: 'GET_FORM_DESCRIPTOR'
};

export default actionTypes;