export const FETCH_DATA_FORMAT_SUCCESS = 'FETCH_DATA_FORMAT_SUCCESS';
export const DELETE_DATA_FORMAT_SUCCESS = 'DELETE_DATA_FORMAT_SUCCESS';
export const CREATE_DATA_FORMAT_SUCCESS = 'CREATE_DATA_FORMAT_SUCCESS';
export const UPDATE_DATA_FORMAT_SUCCESS = 'UPDATE_DATA_FORMAT_SUCCESS';
export const SET_UPDATING_ITEM = 'SET_UPDATING_ITEM';