export const FETCH_DATA_TABLE_SUCCESS = 'FETCH_DATA_TABLE_SUCCESS';
export const DELETE_DATA_TABLE_SUCCESS = 'DELETE_DATA_TABLE_SUCCESS';
export const CREATE_DATA_TABLE_SUCCESS = 'CREATE_DATA_TABLE_SUCCESS';
export const UPDATE_DATA_TABLE_SUCCESS = 'UPDATE_DATA_TABLE_SUCCESS';

export const SET_UPDATING_ITEM = 'SET_UPDATING_ITEM';
export const SORT_DATA_TABLE = "SORT_DATA_FORMAT";
export const CLOSE_OR_OPEN_MODEL_INFO = 'CLOSE_OR_OPEN_MODEL_INFO';
export const CLOSE_OR_OPEN_MODEL_CHANGE = 'CLOSE_OR_OPEN_MODEL_CHANGE';