const actionTypes = {
    GET_TABLE_SUCCESS: 'GET_TABLE_SUCCESS',
    GET_TABLE_ERROR: 'GET_TABLE_ERROR',
    CLEAR_TABLE: 'CLEAR_TABLE',
    UPDATE_TABLE: 'UPDATE_TABLE',
    SET_UPDATING_ITEM: 'SET_UPDATING_ITEM'
};

export default actionTypes;