export default { 
    GET_AUTH_TOKEN_SUCCESS: 'GET_AUTH_TOKEN_SUCCESS',
    GET_AUTH_TOKEN_ERROR: 'GET_AUTH_TOKEN_ERROR',
    CLEAR_AUTH_TOKEN: 'CLEAR_AUTH_TOKEN'
    //LOGOUT: 'LOGOUT',
    //ERROR_REFRESH_TOKEN_EXPIRED: 'Refresh token is expired',
    //ERROR_INVALID_USERNAME_OR_PASSWORD: 'Invalid username or password'
};
